# Generated by Django 3.2 on 2026-09-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='estado_mewasdo',
        ),
        migrations.AddField(
            model_name='mesa',
            name='estado_mesa',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre_plato',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='ingrediente',
            unique_together={('nombre_ingrediente', 'unidad_medida')},
        ),
    ]
