# Generated by Django 3.2 on 2026-09-02 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoXCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='descripcion',
            new_name='descripcion_cargo',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='nombre',
            new_name='nombre_cargo',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='apellido',
            new_name='apellido_empleado',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='email',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='nombre',
            new_name='nombre_empleado',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='tipo_asistecia',
        ),
        migrations.AddField(
            model_name='empleado',
            name='debe_cambiar_contrasena',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='user_auto',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empleados.cargo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tipopermiso',
            name='modulo',
            field=models.CharField(choices=[('platos', 'Platos'), ('bebidas', 'Bebidas'), ('ingredientes', 'Ingredientes'), ('categorias', 'Categorías'), ('empleados', 'Empleados'), ('cargos', 'Cargos'), ('comandas', 'Comandas'), ('mesas', 'Mesas'), ('ventas', 'Ventas'), ('caja', 'Caja'), ('gastos', 'Gastos'), ('reportes', 'Reportes')], max_length=50),
        ),
        migrations.DeleteModel(
            name='TipoAsistenia',
        ),
        migrations.AddField(
            model_name='permisoxcargo',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.cargo'),
        ),
        migrations.AddField(
            model_name='permisoxcargo',
            name='tipo_permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.tipopermiso'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='tipo_asistencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empleados.tipoasistencia'),
            preserve_default=False,
        ),
    ]
