# Generated by Django 3.2 on 2026-09-07 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_auto_20260902_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='nivel_acceso',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='permisoxcargo',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
