# Generated by Django 3.2 on 2026-09-08 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_auto_20260907_1120'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipopermiso',
            unique_together={('modulo', 'accion')},
        ),
        migrations.RemoveField(
            model_name='tipopermiso',
            name='cargo',
        ),
    ]
