# Generated by Django 3.2 on 2026-09-15 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_remove_cargo_id_from_tipopermiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='nombre_cargo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleados.cargo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='permisoxcargo',
            unique_together={('cargo', 'tipo_permiso')},
        ),
    ]
