# Generated by Django 6.1 on 2026-08-24 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Proyecto',
        ),
    ]
