# Generated by Django 6.1 on 2026-08-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_rename_portfolio_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tecnologias',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.FilePathField(path='/img'),
        ),
    ]
