# Generated by Django 3.2 on 2026-08-25 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_plato_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='descripcion',
        ),
    ]
