# Generated by Django 3.2 on 2026-09-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id_mesa', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField(verbose_name='Capacidad')),
                ('numero_mesa', models.IntegerField(unique=True, verbose_name='Número de Mesa')),
                ('estado_mesa', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'db_table': 'mesas',
                'ordering': ['numero_mesa'],
            },
        ),
    ]
