# Generated by Django 3.2 on 2026-09-15 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20260915_1023'),
        ('empleados', '0005_auto_20260915_1023'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id_comanda', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('estado_comanda', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En Preparación'), ('entregado', 'Entregado'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('total_comanda', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('empleado', models.ForeignKey(db_column='empleado_id', on_delete=django.db.models.deletion.CASCADE, related_name='comandas', to='empleados.empleado', unique=True, verbose_name='Mozo')),
                ('mesa', models.ForeignKey(db_column='mesa_id', on_delete=django.db.models.deletion.CASCADE, related_name='comandas', to='ventas.mesa', unique=True, verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'db_table': 'ventas_comanda',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='DetalleComanda',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('plato', 'Plato'), ('bebida', 'Bebida')], max_length=10, verbose_name='Tipo')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('bebida', models.ForeignKey(blank=True, db_column='bebida_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.bebida', verbose_name='Bebida')),
                ('comanda', models.ForeignKey(db_column='comanda_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.comanda', verbose_name='Comanda')),
                ('plato', models.ForeignKey(blank=True, db_column='plato_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.plato', verbose_name='Plato')),
            ],
            options={
                'verbose_name': 'Detalle de Comanda',
                'verbose_name_plural': 'Detalles de Comandas',
                'db_table': 'ventas_detallecomanda',
            },
        ),
    ]
