# Generated by Django 3.2 on 2026-09-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_comanda_detallecomanda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comanda',
            old_name='observaciones',
            new_name='observaciones_comanda',
        ),
        migrations.RenameField(
            model_name='detallecomanda',
            old_name='id_detalle',
            new_name='id_detalle_com',
        ),
        migrations.RemoveField(
            model_name='detallecomanda',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detallecomanda',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='detallecomanda',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='detallecomanda',
            name='tipo',
        ),
        migrations.AddField(
            model_name='detallecomanda',
            name='cant_bebida',
            field=models.IntegerField(default=1, verbose_name='Cantidad Bebida'),
        ),
        migrations.AddField(
            model_name='detallecomanda',
            name='cant_plato',
            field=models.IntegerField(default=1, verbose_name='Cantidad Platos'),
        ),
    ]
