# Generated by Django 3.2 on 2026-09-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20260915_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallecomanda',
            old_name='cant_bebida',
            new_name='cant_bebiba',
        ),
    ]
