# Generated by Django 3.2 on 2026-09-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_rename_cant_bebida_detallecomanda_cant_bebiba'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallecomanda',
            old_name='cant_bebiba',
            new_name='cant_bebida',
        ),
    ]
