# Generated by Django 3.2 on 2026-08-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
