# Generated by Django 3.2 on 2026-08-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_remove_plato_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plato',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
