# Generated by Django 3.2 on 2026-09-01 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria_plato', models.CharField(max_length=100, unique=True)),
                ('descripcion_categoria_plato', models.TextField(blank=True, default='')),
                ('estado_categoria_plato', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ingrediente', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramo'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'mililitros'), ('u', 'Unidades')], max_length=50)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado_ingrediente', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mesa', models.IntegerField(unique=True)),
                ('capacidad', models.IntegerField()),
                ('estado_mewasdo', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada')], default='disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoBebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_bebida', models.CharField(max_length=50)),
                ('descripcion_tipo_bebida', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plato', models.CharField(max_length=100)),
                ('precio_plato', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_plato', models.TextField(blank=True, default='')),
                ('estado_plato', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoriaplato')),
                ('ingredientes', models.ManyToManyField(through='inventario.DetallePlato', to='inventario.Ingrediente')),
            ],
        ),
        migrations.AddField(
            model_name='detalleplato',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ingrediente'),
        ),
        migrations.AddField(
            model_name='detalleplato',
            name='plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.plato'),
        ),
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.tipobebida')),
            ],
        ),
    ]
